# GitHub Actions Workflow responsible for cleaning up the WXT React Template repository from the template-specific files and configurations.
# This workflow is supposed to be triggered automatically when a new template-based repository has been created.

name: Template Cleanup

on:
  push:
    branches: [main]

jobs:
  # Run a cleaning process only if the workflow is triggered by the non-"npm-package-template" repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'react-components-template'
    permissions:
      contents: write
      actions: write
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Get repository description
        id: get_description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}" | jq -r .description)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_OUTPUT

      # Cleanup project
      - name: Cleanup
        uses: ryohidaka/nodejs-cleanup@v1.5.4
        with:
          description: ${{ steps.get_description.outputs.DESCRIPTION }}
          excluded: "CHANGELOG.md, .github/FUNDING.yml, .github/workflows/template-cleanup.yml, .github/workflows/code-cov.yml"
          template-dir: "templates"
          remove-template-dir: true
          pre-commit-script: |
            npm run format
            npm run build
